//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testing5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aduan_whatsapp
    {
        public int reportID { get; set; }
        public string RefNo { get; set; }
        public string Pengadu { get; set; }
        public string AduanWhatsapp { get; set; }
        public string Jenis_Aduan { get; set; }
        public Nullable<System.DateTime> Tarikh_Aduan { get; set; }
        public Nullable<System.DateTime> Tarikh_Aduan_Selesai { get; set; }
        public string Tindakan { get; set; }
        public string Images { get; set; }
    }
}
